apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: tmux-server
  namespace: tmux-server
spec:
  hostnames:
    - tmux.holdenitdown.net
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: default-gateway
      namespace: ingress
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: tmux-server
          port: 8080
